---
jobs:
  - name: deploy-feedback-bot
    plan:
    - get: get-source-code
      public: true
      trigger: true
    - task: build-artifact
      file: git-repo/ci/tasks/build-artifact.yml
    - put: deploy-app
      params:
        manifest: git-repo/manifest.yml
        path: build-output/cfsummit-app-0.0.1-SNAPSHOT.jar

resources:
- name: get-source-code
  type: git
  source:
    uri: {{GIT_REPO}}
    branch: {{GIT_BRANCH}}
    private_key: {{GIT_PRIVATE_KEY}}

- name: deploy-app
  type: cf
  source:
    api: {{CF_API}}
    username: {{CF_USER}}
    password: {{CF_PASS}}
    organization: {{CF_ORG}}
    space: {{CF_SPACE}}
    skip_cert_check: true
